# Generated by Django 4.1.3 on 2022-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='html',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='caption',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='html',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='pages',
            name='html',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
